// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace djfoxer.VisualStudio.MakeTheSound
{
    static class Vsix
    {
        public const string Id = "cb63fe1e-356e-426d-abdf-9237436faf11";
        public const string Name = "Make The Sound";
        public const string Description = @"Make The Sound is an extension for Visual Studio that adds sounds to your IDE.";
        public const string Language = "en-US";
        public const string Version = "0.2.2";
        public const string Author = "djfoxer";
        public const string Tags = "sound events music effect build save warnings";
    }
}
