// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace djfoxer.VisualStudio.MakeTheSound
{
    static class Vsix
    {
        public const string Id = "djfoxer.VisualStudio.MakeTheSound.6c68651b-5dcd-4946-a9db-ef2073702bbc";
        public const string Name = "Make The Sound";
        public const string Description = @"Make The Sound - extension for Visual Studio that add sounds for your best IDE";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "djfoxer";
        public const string Tags = "sound events music effect build save warnings";
    }
}
